import { gql } from '@apollo/client'

/**
 * This is now used for type generated by codegen
 */
export const jobDetail = gql`
  fragment JobFragment on Job {
    id
    title
    date
    description
    company {
      id
      name
    }
  }
`
